package unii.draft.mtg.parings.database.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAYER_DRAFT_JOIN_TABLE".
 */
public class PlayerDraftJoinTable {

    private Long id;
    private Integer PlayerMatchPoints;
    private Float PlayerMatchOverallWin;
    private Float OponentsMatchOveralWins;
    private Float PlayerGamesOverallWin;
    private Float OponentsGamesOverallWin;
    private Boolean Dropped;
    private Integer playerPlace;
    private Long playerDraftJoinTableId;
    private Long draftPlayerJoinTableId;

    public PlayerDraftJoinTable() {
    }

    public PlayerDraftJoinTable(Long id) {
        this.id = id;
    }

    public PlayerDraftJoinTable(Long id, Integer PlayerMatchPoints, Float PlayerMatchOverallWin, Float OponentsMatchOveralWins, Float PlayerGamesOverallWin, Float OponentsGamesOverallWin, Boolean Dropped, Integer playerPlace, Long playerDraftJoinTableId, Long draftPlayerJoinTableId) {
        this.id = id;
        this.PlayerMatchPoints = PlayerMatchPoints;
        this.PlayerMatchOverallWin = PlayerMatchOverallWin;
        this.OponentsMatchOveralWins = OponentsMatchOveralWins;
        this.PlayerGamesOverallWin = PlayerGamesOverallWin;
        this.OponentsGamesOverallWin = OponentsGamesOverallWin;
        this.Dropped = Dropped;
        this.playerPlace = playerPlace;
        this.playerDraftJoinTableId = playerDraftJoinTableId;
        this.draftPlayerJoinTableId = draftPlayerJoinTableId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPlayerMatchPoints() {
        return PlayerMatchPoints;
    }

    public void setPlayerMatchPoints(Integer PlayerMatchPoints) {
        this.PlayerMatchPoints = PlayerMatchPoints;
    }

    public Float getPlayerMatchOverallWin() {
        return PlayerMatchOverallWin;
    }

    public void setPlayerMatchOverallWin(Float PlayerMatchOverallWin) {
        this.PlayerMatchOverallWin = PlayerMatchOverallWin;
    }

    public Float getOponentsMatchOveralWins() {
        return OponentsMatchOveralWins;
    }

    public void setOponentsMatchOveralWins(Float OponentsMatchOveralWins) {
        this.OponentsMatchOveralWins = OponentsMatchOveralWins;
    }

    public Float getPlayerGamesOverallWin() {
        return PlayerGamesOverallWin;
    }

    public void setPlayerGamesOverallWin(Float PlayerGamesOverallWin) {
        this.PlayerGamesOverallWin = PlayerGamesOverallWin;
    }

    public Float getOponentsGamesOverallWin() {
        return OponentsGamesOverallWin;
    }

    public void setOponentsGamesOverallWin(Float OponentsGamesOverallWin) {
        this.OponentsGamesOverallWin = OponentsGamesOverallWin;
    }

    public Boolean getDropped() {
        return Dropped;
    }

    public void setDropped(Boolean Dropped) {
        this.Dropped = Dropped;
    }

    public Integer getPlayerPlace() {
        return playerPlace;
    }

    public void setPlayerPlace(Integer playerPlace) {
        this.playerPlace = playerPlace;
    }

    public Long getPlayerDraftJoinTableId() {
        return playerDraftJoinTableId;
    }

    public void setPlayerDraftJoinTableId(Long playerDraftJoinTableId) {
        this.playerDraftJoinTableId = playerDraftJoinTableId;
    }

    public Long getDraftPlayerJoinTableId() {
        return draftPlayerJoinTableId;
    }

    public void setDraftPlayerJoinTableId(Long draftPlayerJoinTableId) {
        this.draftPlayerJoinTableId = draftPlayerJoinTableId;
    }

}
